# Naive Bayes Classifier

Welcome to your next lab! You will build Naive Bayes Classifier.

You will classify spam/ham messages.

**You will learn to:**
- Build the general architecture of a learning algorithm with OOP in mind:
    - Helper functions
        - Preprocessing data
    - Main Model Class
        - Training
        - Prediction 


## 1 - Packages ##

First, let's run the cell below to import all the packages that you will need during this assignment.
- [numpy](www.numpy.org) is the fundamental package for scientific computing with Python.
- [pandas](https://pandas.pydata.org/) is a library providing a convenient work with data.
- [re](https://docs.python.org/3/library/re.html) is for regex

In [314]:
import pandas as pd
import numpy as np
import re

## 2 - Overview of the Problem set ##

**Problem Statement**: You are given a dataset  containing:
    - a training set of m_train examples
    - a test set of m_test examples
    - each example is a message that belongs to a particular class: ham or spam.

Let's get more familiar with the dataset. Load the data by running the following code.

We won't divide our data to features(X) and target(Y) here, because we need to preprocess it in a special way.

In [315]:
# Loading the data 

def load_data():
    df = pd.read_csv('spam.csv', encoding='latin-1')
    df_for_tests = df.head()
#     print(df)
    
    idx = np.arange(df.shape[0])
    np.random.shuffle(idx)
#     print(idx)
    
    train_set_size = int(df.shape[0] * 0.8)

    train_set = df.loc[idx[:train_set_size]]
    test_set = df.loc[idx[train_set_size:]]
#     print(train_set)
#     print(test_set)
    
    return train_set, test_set, df_for_tests

In [316]:
train_set, test_set, df_for_tests = load_data()

## 3 - Naive Bayes Classifier
**Mathematical expression of the algorithm**:


This algorithm is based on Bayes' theorem:
    $$ \begin{equation}
    P(A_{j}\hspace{0.1cm}\rvert\hspace{0.1cm}x_{1},\dots,x_{n}) = \frac{P(x_{1},\dots,x_{n}\hspace{0.1cm}\rvert\hspace{0.1cm}A_{j})P(A_{j})}{P(x_{1},\dots,x_{n})} 
    \end{equation}$$
    
Ignoring denominator (because it stays the same for all cases):

$$ \begin{equation}
    P(A_{j})P(x_{1},\dots,x_{n}\hspace{0.1cm}\rvert\hspace{0.1cm}A_{j}) = P(A_{j}, x_{1},\dots,x_{n}) = \\
  \hspace{1cm} = P(x_{1}\hspace{0.1cm}\rvert\hspace{0.1cm}x_{2},\dots,x_{n}, A_{j})P(x_{2}\hspace{0.1cm}\rvert\hspace{0.1cm}x_{3}, \dots ,x_{n}, A_{j})\dots P(x_{n-1}\hspace{0.1cm}\rvert\hspace{0.1cm}x_{n}, A_{j}) \approx \\
  \hspace{1cm}
  \end{equation}$$
By making an assumption that the $x_{i}$ are conditionally independent of each other:
$$ \begin{equation} \approx P(A_{j}) \prod_{i=1}^{n} P(x_{i}\hspace{0.1cm}\rvert\hspace{0.1cm}A_{j})
   \end{equation}$$
   
We can calculate the probability, if we know the prior probability:

$$ \begin{equation}
    y^{*} = \operatorname*{arg\,max}_{j} \big(P(A_{j}) \prod_{i=1}^{n} P(x_{i}\hspace{0.1cm}\rvert\hspace{0.1cm}A_{j})\big)
   \end{equation}$$
   
   
Due to floating point underflow, the above is usually replaced with the numerically tractable expression:

$$ \begin{equation}
    y^{*} = \operatorname*{arg\,max}_{j} \big( \ln(P(A_{j})) + \sum_{i=1}^{n} \ln(P(x_{i}\hspace{0.1cm}\rvert\hspace{0.1cm}A_{j})) \big)
   \end{equation}$$
   
   
#### Laplace smoothing

In statistics, additive smoothing, also called Laplace smoothing, or Lidstone smoothing, is a technique that is used to smooth categorical data. Given an observation 
$\begin{equation}
    x = (x_{1}\, \dots \,x_{k})
 \end{equation}$ from a multinomial distribution with N trials, a "smoothed" version of the data gives the estimator:

$$ \begin{equation}
    \theta_i = \frac{x_{i} + \alpha}{N + \alpha k}
   \end{equation}$$

where the pseudocount 
$\begin{equation}
    \alpha > 0
 \end{equation}$ is the smoothing parameter (
$\begin{equation}
    \alpha = 0
 \end{equation}$ corresponds to no smoothing).

### 3.1 - Preprocessing the data 

Our data consists of different messages. Messages contain some excess symbols, which don't affect the content of the text, but add noise to the data.
For example: "Does not \\operate 66.7 after  & lt;# & gt;  or what". 

Let's clean our data and leave only letters a-z, A-Z, numbers 0-9 and cast all letters to lowercase, replace double to n spaces with just one space, remove trailing spaces.

In [365]:
# Clean the data

def clean_data(message):
    
    """ 
    Returns string which consists of message words
    
    Argument:
    message -- message from dataset; 
        type(message) -> <class 'str'>
    
    Returns:
    result -- cleaned message, which contains only letters a-z, and numbers 0-9, with only one space between words;
        type(clean_data(message)) -> <class 'str'>
    
    """
    
    ### START CODE HERE ###
#     print (re.findall(r"[\w']+", message))
    t = re.split('\s+', message)
    result = str()
#     print(t)
    for i in range(len(t)):
        t[i] = re.sub('[^\w]', '', t[i])
    t = list(filter(lambda x: (x != ''), t))
    return ' '.join(t).lower()
    
    ### END CODE HERE ###

In [366]:
sentence = 'Does not  \\operate 66.7 after & lt;# & gt; or what'
print('cleaned: ',clean_data(sentence))

cleaned:  does not operate 667 after lt gt or what


**Expected Output**: 

<table style="width:50%">
    <tr>
       <td> **cleaned:** </td>
       <td> does not operate 667 after lt gt or what </td>
    </tr>
    

</table>

Now let's clean each sentence and split data on features(X) and target(Y)

In [430]:
# Preparation data for model

def prep_for_model(train_set, test_set):
    
    """ 
    Returns arrays of train/test features(words) and train/test targets(labels)
    
    Arguments:
    train_set -- train dataset, which consists of train messages and labels; 
        type(train_set) -> pandas.core.frame.DataFrame
    test_set -- test dataset, which consists of test messages and labels; 
        type(train_set) -> pandas.core.frame.DataFrame
    
    Returns:
    train_set_x -- array which contains lists of words of each cleaned train message; 
        (type(train_set_x) ->numpy.ndarray[list[str]], train_set_x.shape = (num_messages,))
    train_set_y -- array of train labels (names of classes), 
        (type(train_set_y) -> numpy.ndarray, train_set_y.shape = (num_messages,))
    test_set_x -- array which contains lists of words of each cleaned test message;
        (type(test_set_x) numpy.ndarray[list[str]], test_set_x.shape = (num_messages,)
    test_set_y -- array of test labels (names of classes), 
        (type(test_set_y) -> numpy.ndarray, test_set_y.shape = (num_messages,))
    
    """
    
    ### START CODE HERE ###
#     print(train_set.shape)
    t1 = list(map(lambda x: clean_data(x), train_set['v2']))
    for i in range(len(t1)):
        t1[i] = t1[i].split()
    train_set_x = np.asarray(t1)
#     train_set_x = np.ndarray(t, shape=(train_set.shape[0],))
    
    train_set_y = np.asarray(list(train_set['v1']))
#     print(train_set_y)
    
    t2 = list(map(lambda x: clean_data(x), test_set['v2']))
    for i in range(len(t2)):
        t2[i] = t2[i].split()
    test_set_x = np.asarray(t2)
#     train_set_x = np.ndarray(t, shape=(train_set.shape[0],))
    
    test_set_y = np.asarray(list(test_set['v1']))
    ### END CODE HERE ###
    
#     print(train_set_x.shape)
    
    
    return train_set_x, train_set_y, test_set_x, test_set_y

train_set_x, train_set_y, test_set_x, test_set_y = prep_for_model(train_set, test_set)

In [431]:
a1, a2, b1, b2 = prep_for_model(df_for_tests.head(3), df_for_tests.tail(2))
print(a2[0], a1[0])
print(b2[0], b1[0])

ham ['go', 'until', 'jurong', 'point', 'crazy', 'available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', 'cine', 'there', 'got', 'amore', 'wat']
ham ['u', 'dun', 'say', 'so', 'early', 'hor', 'u', 'c', 'already', 'then', 'say']


**Expected Output**: 

<table style="width:40%">
    <tr>
       <td> **ham:** </td>
       <td> ['go', 'until', 'jurong', 'point', 'crazy', 'available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', 'cine', 'there', 'got', 'amore', 'wat'] </td>
    </tr>
    <tr>
       <td> **ham:** </td>
       <td> ['u', 'dun', 'say', 'so', 'early', 'hor', 'u', 'c', 'already', 'then', 'say']
 </td>
    </tr>

</table>

Now let's check words in each category

In [432]:
# Check words in categories

def categories_words(x_train, y_train):
    
    """
    Returns arrays of features(words) in each category and in both categories
    
    Arguments:
    x_train -- array which contains lists of words of each cleaned train message; 
        (type(x_train) -> numpy.ndarray[list[str]], x_train.shape = (num_messages,))
    
    Returns:
    all_words_list -- array of all words in both categories;
        (type(all_words_list) -> numpy.ndarray[str], all_words_list.shape = (num_words,))
    ham_words_list -- array of words in 'ham' class;
        (type(ham_words_list) -> numpy.ndarray[str], ham_words_list.shape = (num_words,))
    spam_words_list -- array of words in 'spam' class;
        (type(spam_words_list) -> numpy.ndarray[str], spam_words_list.shape = (num_words,))        
    """
    all_words_list = []
    ham_words_list = []
    spam_words_list = []
    
    ### START CODE HERE ###
#     print(y_train.shape[0])
    for i in range(y_train.shape[0]):
        if y_train[i] == 'ham':
            ham_words_list += x_train[i]
        if y_train[i] == 'spam':
            spam_words_list += x_train[i]
            
    all_words_list = ham_words_list + spam_words_list
    
    ### END CODE HERE ###
    
    return all_words_list, ham_words_list, spam_words_list

all_words_list_a1, ham_words_list_a1, spam_words_list_a1 = categories_words(a1, a2)

In [433]:
print('first five "ham" words of a1: ', ham_words_list_a1[:5])

first five "ham" words of a1:  ['go', 'until', 'jurong', 'point', 'crazy']


**Expected Output**: 

<table style="width:40%">
    <tr>
       <td> **first five "ham" words of a1:** </td>
       <td> ['go' 'until' 'jurong' 'point' 'crazy'] </td>
    </tr>

</table>

### 3.2 Model

In [412]:
???

import os
from collections import Counter
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.svm import SVC, NuSVC, LinearSVC


class Naive_Bayes(object):
    """
    Parameters:
    -----------
    alpha: int
        The smoothing coeficient.
    """
    def __init__(self, alpha):
        self.alpha = alpha
        
#         self.train_set_x = None
#         self.train_set_y = None
        
        self.all_words_list = []
        self.ham_words_list = []
        self.spam_words_list = []
    
    def fit(self, train_set_x, train_set_y):
        
#         print(train_set_x)
#         return
        
        # Generate all_words_list, ham_words_list, spam_words_list using function 'categories_words'; 
        # Calculate probability of each word in both categories
        ### START CODE HERE ### 
        self.all_words_list, self.ham_words_list, self.spam_words_list = categories_words(train_set_x, train_set_y) 
#         print(self.ham_words_list)   
        unique_elements, counts_elements = np.unique(self.spam_words_list, return_counts=True)
#         print(np.asarray((unique_elements, counts_elements)))
        ### END CODE HERE ### 
    


        # Create a dictionary of words with its frequency

#         train_dir = 'train-mails'
#         dictionary = make_Dictionary(train_set_x)

#         # Prepare feature vectors per training mail and its labels

#         train_labels = np.zeros(702)
#         train_labels[351:701] = 1
#         train_matrix = extract_features(train_dir)

        # Training SVM and Naive bayes classifier
        print(train_set_x)
        
        from sklearn.datasets import make_classification
        X, y = make_classification(n_features=4, random_state=0)
        print(X)
        model1 = MultinomialNB()
        model2 = LinearSVC()
        model1.fit(train_set_x,train_set_y)
        model2.fit(train_set_x,train_set_y)

#         # Test the unseen mails for Spam
#         test_dir = 'test-mails'
#         test_matrix = extract_features(test_dir)
#         test_labels = np.zeros(260)
#         test_labels[130:260] = 1
#         result1 = model1.predict(test_matrix)
#         result2 = model2.predict(test_matrix)
     
        
    def predict(self, test_set_x):
        
        # Return list of predicted labels for test set; type(prediction) -> list, len(prediction) = len(test_set_y)
        ### START CODE HERE ###
#         prediction = model.predict(self.test_set_x)
            
        ### END CODE HERE ### 
        return prediction

## 4 - Training

First of all, we should define a smoothing coeficient (`alpha`).

In [413]:
a = 1

Now we can initialize our model:

In [414]:
model = Naive_Bayes(alpha=a)

Let's train our model:

In [415]:
model.fit(train_set_x, train_set_y)

[list(['eh', 'u', 'remember', 'how', '2', 'spell', 'his', 'name', 'yes', 'i', 'did', 'he', 'v', 'naughty', 'make', 'until', 'i', 'v', 'wet'])
 list(['are', 'you', 'willing', 'to', 'go', 'for', 'aptitude', 'class'])
 list(['i', 'will', 'reach', 'ur', 'home', 'in', 'ltgt', 'minutes']) ...
 list(['our', 'ride', 'equally', 'uneventful', 'not', 'too', 'many', 'of', 'those', 'pesky', 'cyclists', 'around', 'at', 'that', 'time', 'of', 'night'])
 list(['cud', 'u', 'tell', 'ppl', 'im', 'gona', 'b', 'a', 'bit', 'l8', 'cos', '2', 'buses', 'hav', 'gon', 'past', 'cos', 'they', 'were', 'full', 'im', 'still', 'waitin', '4', '1', 'pete', 'x'])
 list(['do', 'u', 'hav', 'any', 'frnd', 'by', 'name', 'ashwini', 'in', 'ur', 'college'])]
[[-7.15602562e-02  2.29553900e-01  2.16543447e-01  6.52739792e-02]
 [-4.03257104e-01  2.00618406e+00  2.02751248e+00  8.50891944e-01]
 [-1.13058206e+00 -2.02959251e-02 -7.10233633e-01 -1.44099108e+00]
 [ 1.83324682e-01 -7.74610354e-01 -7.66054695e-01 -2.93668633e-01]
 [-2.86

ValueError: setting an array element with a sequence.

## 5 - Making predictions

In [393]:
y_predictions = model.predict(test_set_x)

NameError: name 'prediction' is not defined

Let's calculate accuracy (accuracy of model must be >0.95):

In [0]:
actual = list(test_set_y)
accuracy = (y_predictions == test_set_y).mean()
print(accuracy)

## 6 - Conclusion
As we can see, our model fits well the hypothesis function to the data.

#### What's next:
1. Try experimenting with the `alpha` to see how this affects the model you have built.
2. Compare the results you have obtained with the `sklearn.naive_bayes.MultinomialNB` model.
3. Try this model in the wild! Select your favorite dataset [here](https://www.kaggle.com/datasets?sortBy=hottest&group=public&page=1&pageSize=20&size=small&filetype=all&license=all&tagids=13303) and play with it.